import { expect, it } from "vitest";
import { EXIT } from "./cells";
import { contacts, fight, retreat, stanceOf } from "./combat";
import { homeOf, queenOf } from "./model";
import { Navigation } from "./navigation";
import { addUnit, egg, world } from "./test-support";
import { createUnit } from "./units";

it("uses factions independently of roles, targets one opponent and applies lethal damage simultaneously", () => {
  const ours = createUnit(8, "warrior", "colony", { x: 2, y: 0 });
  const first = createUnit(2, "warrior", "raiders", ours.cell);
  const second = createUnit(3, "warrior", "raiders", ours.cell);
  ours.hp = 8;
  first.hp = 4;
  const units = [second, ours, first];
  fight(units, 0.95);
  expect(units.map((u) => u.hp)).toEqual([24, 8, 4]);
  fight(units, 0.05);
  expect([ours.hp, first.hp, second.hp]).toEqual([0, 0, 24]);
});
it("uses individual bite strength and does not attack a different cell or friendly role", () => {
  const warrior = createUnit(1, "warrior", "colony", { x: 8, y: 2 });
  warrior.bite = 2;
  const scout = createUnit(2, "scout", "colony", warrior.cell);
  const enemy = createUnit(3, "warrior", "raiders", { x: 8, y: 3 });
  fight([warrior, scout, enemy], 1);
  expect([warrior.hp, scout.hp, enemy.hp]).toEqual([24, 10, 24]);
  enemy.cell = warrior.cell;
  fight([warrior, enemy], 1);
  expect([warrior.hp, enemy.hp]).toEqual([20, 22]);
});
it("includes the queen in contact and excludes dead units and scouts away on expeditions", () => {
  const queen = createUnit(0, "queen", "colony", { x: 10, y: 3 });
  const enemy = createUnit(1, "warrior", "raiders", queen.cell);
  const scout = createUnit(2, "scout", "colony", queen.cell);
  scout.job = { kind: "forage", phase: "away", exit: { x: -1, y: 0 }, remaining: 5 };
  expect(contacts([queen, enemy, scout]).targets.has(scout.id)).toBe(false);
  fight([queen, enemy, scout], 1);
  expect([queen.hp, enemy.hp, scout.hp]).toEqual([20, 20, 10]);
  queen.hp = 0;
  expect(contacts([queen, enemy, scout]).targets.size).toBe(0);
  fight([queen, enemy, scout], 10);
  expect(queen.hp).toBe(0);
});
it("heals by one after two peaceful seconds, caps at maximum and resets both clocks on contact changes", () => {
  const ours = createUnit(1, "warrior", "colony", { x: 8, y: 2 });
  const enemy = createUnit(2, "warrior", "raiders", { x: 8, y: 3 });
  ours.hp = 22;
  for (let i = 0; i < 39; i++) fight([ours, enemy], 0.05);
  expect(ours.hp).toBe(22);
  fight([ours, enemy], 0.05);
  expect(ours.hp).toBe(23);
  fight([ours, enemy], 1.95);
  enemy.cell = ours.cell;
  fight([ours, enemy], 0.05);
  expect(ours.hp).toBe(23);
  expect(ours.healWait).toBe(0);
  enemy.cell = { x: 8, y: 3 };
  fight([ours, enemy], 1.95);
  expect(ours.hp).toBe(23);
  expect(ours.attackWait).toBe(0);
  fight([ours, enemy], 0.05);
  expect(ours.hp).toBe(24);
  fight([ours, enemy], 20);
  expect(ours.hp).toBe(24);
  expect(ours.healWait).toBe(0);
});

it("keeps consecutive attack cadence and healed progress between hits without favoring array order", () => {
  const ours = createUnit(10, "queen", "colony", { x: 8, y: 2 });
  const enemy = createUnit(2, "queen", "raiders", ours.cell);
  const friend = createUnit(1, "queen", "colony", ours.cell);
  const units = [ours, enemy, friend];
  for (let i = 0; i < 39; i++) fight(units, 0.05);
  expect([ours.hp, friend.hp, enemy.hp]).toEqual([24, 20, 16]);
  fight(units, 0.05);
  expect([ours.hp, friend.hp, enemy.hp]).toEqual([24, 16, 8]);
  expect(enemy.attackWait).toBeCloseTo(0, 8);
});

it("retains fractional time across repeated hits and heals for short steps that do not divide the period", () => {
  const ours = createUnit(1, "queen", "colony", { x: 8, y: 2 });
  const enemy = createUnit(2, "queen", "raiders", ours.cell);
  for (let i = 0; i < 100; i++) fight([ours, enemy], 0.03);
  expect([ours.hp, enemy.hp]).toEqual([12, 12]);
  const wounded = createUnit(3, "warrior", "colony", { x: 8, y: 3 });
  wounded.hp = 1;
  for (let i = 0; i < 66; i++) fight([wounded], 0.03);
  expect(wounded.hp).toBe(1);
  fight([wounded], 0.03);
  expect(wounded.hp).toBe(2);
  for (let i = 0; i < 66; i++) fight([wounded], 0.03);
  expect(wounded.hp).toBe(2);
  fight([wounded], 0.03);
  expect(wounded.hp).toBe(3);
});
it("does not bank healing while full, including after returning to maximum health", () => {
  const unit = createUnit(1, "warrior", "colony", { x: 8, y: 2 });
  fight([unit], 9);
  expect(unit.healWait).toBe(0);
  unit.hp = 23;
  fight([unit], 1.95);
  expect(unit.hp).toBe(23);
  fight([unit], 0.1);
  expect(unit.hp).toBe(24);
  expect(unit.healWait).toBe(0);
});

it("keeps a third fighter of a side out of the front: it neither hits nor takes damage", () => {
  const ours = [1, 2, 3].map((id) => createUnit(id, "warrior", "colony", { x: 8, y: 2 }));
  const theirs = [4, 5, 6].map((id) => createUnit(id, "warrior", "raiders", { x: 8, y: 2 }));
  const units = [...ours, ...theirs];
  const contact = contacts(units);
  expect([...contact.targets.keys()].sort((a, b) => a - b)).toEqual([1, 2, 4, 5]);
  expect(contact.targets.get(1)).toBe(theirs[0]);
  expect(contact.targets.get(2)).toBe(theirs[1]);
  expect([...contact.blocked].sort((a, b) => a - b)).toEqual([1, 2, 3, 4, 5, 6]);
  fight(units, 1, contact);
  expect(units.map((unit) => unit.hp)).toEqual([20, 20, 24, 20, 20, 24]);
});
it("focuses spare front slots on the same opponent when the other side is outnumbered", () => {
  const ours = [1, 2].map((id) => createUnit(id, "warrior", "colony", { x: 8, y: 2 }));
  const enemy = createUnit(3, "warrior", "raiders", { x: 8, y: 2 });
  fight([...ours, enemy], 1);
  expect(enemy.hp).toBe(16);
  expect(ours.map((unit) => unit.hp)).toEqual([20, 24]);
});
it("lets an evading unit pass without fighting and without blocking its own side", () => {
  const worker = createUnit(1, "worker", "colony", { x: 8, y: 2 });
  const scout = createUnit(2, "scout", "raiders", worker.cell);
  const contact = contacts([worker, scout]);
  expect(contact.targets.size).toBe(0);
  expect(contact.blocked.size).toBe(0);
  fight([worker, scout], 1, contact);
  expect([worker.hp, scout.hp]).toEqual([8, 10]);
});
it("hits an evading unit only through a free front slot of the attacking side", () => {
  const first = createUnit(1, "warrior", "colony", { x: 8, y: 2 });
  const second = createUnit(2, "warrior", "colony", { x: 8, y: 2 });
  const scout = createUnit(3, "scout", "colony", { x: 8, y: 2 });
  const raiders = [4, 5].map((id) => createUnit(id, "warrior", "raiders", { x: 8, y: 2 }));
  fight([first, second, scout, ...raiders], 1);
  expect(scout.hp).toBe(10);
  fight([first, scout, ...raiders], 1);
  expect(scout.hp).toBe(6);
});
it("treats a fleeing fighter as evading: it stops blocking, stops hitting and can still be hit", () => {
  const ours = createUnit(1, "warrior", "colony", { x: 8, y: 2 });
  const enemy = createUnit(2, "warrior", "raiders", ours.cell);
  ours.fleeing = true;
  ours.hp = 5;
  const contact = contacts([ours, enemy]);
  expect(contact.blocked.has(ours.id)).toBe(false);
  expect(contact.targets.has(ours.id)).toBe(false);
  expect(contact.targets.get(enemy.id)).toBe(ours);
  fight([ours, enemy], 1, contact);
  expect([ours.hp, enemy.hp]).toEqual([1, 24]);
});
it("holds healing while queued in a contested cell and resumes it outside contact", () => {
  const ours = [1, 2, 3].map((id) => createUnit(id, "warrior", "colony", { x: 8, y: 2 }));
  const enemy = createUnit(4, "warrior", "raiders", { x: 8, y: 2 });
  const queued = ours[2];
  if (!queued) throw new Error("queued");
  queued.hp = 10;
  fight([...ours, enemy], 2);
  expect(queued.hp).toBe(10);
  queued.cell = { x: 8, y: 3 };
  fight([...ours, enemy], 2);
  expect(queued.hp).toBe(11);
});
it("sends a wounded ant home and a wounded raider to the exit, then clears the flight once healed", () => {
  const game = world();
  const navigation = new Navigation(game.colony);
  const worker = addUnit(game, "worker", { x: 8, y: 3 });
  const raider = addUnit(game, "scout", { x: 8, y: 3 }, "raiders");
  const soldier = addUnit(game, "warrior", { x: 8, y: 3 });
  worker.hp = 4;
  raider.hp = 5;
  soldier.hp = 6;
  retreat(game, navigation);
  expect([worker.fleeing, raider.fleeing, soldier.fleeing]).toEqual([false, false, false]);
  worker.hp = 3;
  raider.hp = 4;
  soldier.hp = 5;
  retreat(game, navigation);
  expect([worker.fleeing, raider.fleeing, soldier.fleeing]).toEqual([true, true, true]);
  expect(worker.job).toEqual({ kind: "flee", destination: homeOf(game) });
  expect(raider.job).toEqual({ kind: "flee", destination: EXIT });
  expect(worker.route.at(-1)).toEqual(homeOf(game));
  expect(stanceOf(soldier)).toBe("evade");
  worker.hp = worker.maxHp;
  raider.hp = raider.maxHp;
  raider.job = { kind: "wander", destination: { x: 8, y: 3 } };
  soldier.hp = soldier.maxHp;
  soldier.job = null;
  retreat(game, navigation);
  expect([worker.fleeing, raider.fleeing, soldier.fleeing]).toEqual([false, false, false]);
  expect(worker.job).toBe(null);
  expect(raider.job).toEqual({ kind: "wander", destination: { x: 8, y: 3 } });
});
it("never makes the queen flee, spares the dead and drops the cargo of a fleeing unit", () => {
  const game = world();
  const navigation = new Navigation(game.colony);
  const queen = queenOf(game);
  if (!queen) throw new Error("queen");
  queen.hp = 1;
  const thief = addUnit(game, "worker", { x: 9, y: 3 }, "raiders");
  const stolen = egg(game, thief.cell);
  game.items = [{ ...stolen, location: { kind: "carried", unitId: thief.id } }];
  thief.hp = 3;
  const dead = addUnit(game, "worker", { x: 8, y: 3 });
  dead.hp = 0;
  retreat(game, navigation);
  expect(queen.fleeing).toBe(false);
  expect(queen.job).toBe(null);
  expect(dead.fleeing).toBe(false);
  expect(game.items.map((entry) => entry.location)).toEqual([{ kind: "cell", cell: { x: 9, y: 3 } }]);
  expect(thief.job).toEqual({ kind: "flee", destination: EXIT });
  const lost = addUnit(game, "worker", { x: 0, y: 9 });
  lost.hp = 3;
  retreat(game, navigation);
  expect(lost.job).toEqual({ kind: "flee", destination: homeOf(game) });
  expect(lost.route).toEqual([]);
});
